"""Data loading utilities for the sarima-bayes forecasting pipeline.

This module provides :func:`load_data` for reading the raw sales Excel
workbook and applying the minimum cleaning steps required before the
preprocessing stage.

Expected input format
---------------------
The input Excel file must contain a sheet (default: ``"Data"``) with the
following structure::

    Row 0:   (blank or metadata — skipped)
    Row 1:   (blank or metadata — skipped)
    Row 2:   column headers  →  Date | SKU | CS | Country | …
    Row 3+:  data rows

Minimum required columns:

- **Date** (str): Period identifier in ``YYYYMM`` format
  (e.g. ``"202201"`` for January 2022).
- **SKU** (int): Numeric product identifier.
- **CS** (float): Sales volume in case-equivalent units (or any demand unit).
- **Country** (str): Market / country code (e.g. ``"US"``, ``"MX"``).

Optional columns (passed through unchanged):

- **Forecast group** (str): Distribution-channel segment used when the
  dataset is split by channel before forecasting.

Additional columns are preserved unchanged.

See ``docs/methodology.md`` for a full column reference and sample rows.

Note:
    For demo purposes, the ``notebooks/demo.ipynb`` notebook generates
    synthetic data in-memory and does **not** require an Excel file.  The
    :func:`load_data` function is only needed when working with real data.
"""

import logging
from typing import Any

import pandas as pd

from sarima_bayes.config import (
    DEFAULT_DATE_FORMAT,
    DEFAULT_SHEET_NAME,
    DEFAULT_SKIP_ROWS,
)

logger = logging.getLogger(__name__)


def load_data(
    route: str,
    sheet_name: str = DEFAULT_SHEET_NAME,
    skip_rows: int = DEFAULT_SKIP_ROWS,
    date_format: str = DEFAULT_DATE_FORMAT,
    fill_na_value: Any = 0,
    invalid_sku_marker: str = "##",
) -> pd.DataFrame:
    """Load and minimally clean a monthly sales Excel workbook.

    Applies the following cleaning steps in order:

    1. Reads the specified worksheet.
    2. Skips ``skip_rows`` meta-header rows to reach column names.
    3. Fills ``NaN`` cells with ``fill_na_value`` (default ``0``).
    4. Drops rows where ``SKU == invalid_sku_marker`` (marks subtotal rows
       in common export formats).
    5. Parses the ``Date`` column from ``YYYYMM`` string to ``pd.Timestamp``.
    6. Casts ``SKU`` to ``int``.
    7. Casts ``CS`` to ``float``.

    Args:
        route: Absolute or relative path to the ``.xlsx`` file.
        sheet_name: Name of the worksheet to read.
            Defaults to ``"Data"``.
        skip_rows: Number of rows to skip before the column header row.
            Defaults to ``2``.
        date_format: ``strptime``-compatible format string for the ``Date``
            column.  Defaults to ``"%Y%m"``.
        fill_na_value: Replacement value for ``NaN`` cells.
            Defaults to ``0``.
        invalid_sku_marker: String value in the ``SKU`` column that marks
            non-data rows (e.g. subtotals generated by Excel pivot exports).
            Defaults to ``"##"``.

    Returns:
        Cleaned ``pd.DataFrame`` with at minimum the columns
        ``["Date", "SKU", "CS", "Country"]``.

    Raises:
        FileNotFoundError: If ``route`` does not point to an existing file.
        KeyError: If the ``"SKU"`` or ``"Date"`` columns are missing.
        ValueError: If ``SKU`` or ``CS`` cannot be cast to their expected types.

    Example:
        >>> df = load_data("data/input/sales.xlsx")
        >>> df.dtypes[["Date", "SKU", "CS"]]
        Date     datetime64[ns]
        SKU               int64
        CS              float64
        dtype: object
    """
    # ── 1. Read Excel ──────────────────────────────────────────────────────────
    try:
        df = pd.read_excel(route, sheet_name=sheet_name)
        logger.info("Loaded '%s' [sheet=%s]", route, sheet_name)
    except FileNotFoundError:
        logger.error("File not found: %s", route)
        raise
    except Exception as exc:
        logger.error("Error reading '%s': %s", route, exc)
        raise

    # ── 2. Skip meta-header rows ───────────────────────────────────────────────
    df = df.iloc[skip_rows:].copy()

    # ── 3. Fill NaN ────────────────────────────────────────────────────────────
    df = df.fillna(fill_na_value)

    # ── 4. Drop invalid SKU marker rows ───────────────────────────────────────
    if "SKU" not in df.columns:
        raise KeyError("Column 'SKU' not found in the data sheet.")
    df = df[df["SKU"] != invalid_sku_marker]

    # ── 5. Parse Date column ────────────────────────────────────────────────────
    if "Date" not in df.columns:
        raise KeyError("Column 'Date' not found in the data sheet.")
    df["Date"] = pd.to_datetime(
        df["Date"].astype(str),
        format=date_format,
        errors="coerce",
    )
    n_unparseable = df["Date"].isnull().sum()
    if n_unparseable:
        logger.warning("Dropping %d rows with unparseable dates.", n_unparseable)
        df = df.dropna(subset=["Date"])

    # ── 6. Cast SKU to int ─────────────────────────────────────────────────────
    try:
        df["SKU"] = df["SKU"].astype(int)
    except (ValueError, TypeError) as exc:
        logger.error("Cannot cast 'SKU' to int: %s", exc)
        raise

    # ── 7. Cast CS to float ────────────────────────────────────────────────────
    try:
        df["CS"] = df["CS"].astype(float)
    except (ValueError, TypeError) as exc:
        logger.error("Cannot cast 'CS' to float: %s", exc)
        raise

    return df
